version: '3.8'

services:
  app:
    container_name: app
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}
    build:
      context: .
      dockerfile: ./db_sql/Dockerfile
    command: bash -c "alembic upgrade head"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - test

  web:
    container_name: web
    image: nginx:1.25.2-alpine
    depends_on:
      - db
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test

  db:
    container_name: postgres
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_postgresql:/var/lib/postgresql/data

volumes:
  db_postgresql:

networks:
  test: