version: '3.8'

services:
  app:
    image: anasti97/backend:latest
    restart: always
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  ds_ml:
    image: bar2les/prosept_competition_2023:latest
    restart: always

  frontend:
    image: yaroslavpatrikeev/prosept_frontend
    command: cp -r /app/dist/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - db

  web:
    image: nginx:latest
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      -  static:/staticfiles
    depends_on:
      - frontend
      - app

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - db_postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d db_dealer -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      - ds_ml

volumes:
  db_postgresql:
  static: