version: '3.8'

services:
  app:
    env_file: .env
    build:
      context: .
      dockerfile: ./db_sql/Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - web

  web:
    image: nginx:1.25.2-alpine
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:15
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - db_postgresql:/var/lib/postgresql/data

volumes:
  db_postgresql:
