version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
     - 8000:8000
    env_file: .env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend./
      dockerfile: Dockerfile
    command: cp -r /app/dist/. /frontend_static/
    ports:
      - 3000:3000
    volumes:
      - static:/frontend_static
    depends_on:
      - db

  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/staticfiles
    depends_on:
      - frontend
      - app

  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file: .env
    volumes:
      - db_postgresql:/var/lib/postgresql/data

volumes:
  db_postgresql:
  static:
