version: '3.8'

services:
  app:
    environment:
      - DATABASE_URL=${DATABASE_URL}
    build:
      context: .
      dockerfile: ./db_sql/Dockerfile
    command: bash -c "alembic upgrade head"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env

  web:
    image: nginx:1.25.2-alpine
    depends_on:
      - db
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_postgresql:/var/lib/postgresql/data

volumes:
  db_postgresql:
