"""Alembic_first_migration

Revision ID: 02ed580b25d5
Revises: 
Create Date: 2023-11-27 19:19:58.960371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02ed580b25d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_dealerprice', sa.Column('markup', sa.Boolean(), nullable=True))
    op.alter_column('marketing_dealerprice', 'product_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('marketing_dealerprice', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.add_column('marketing_productdealerkey', sa.Column('date_markup', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketing_productdealerkey', 'date_markup')
    op.alter_column('marketing_dealerprice', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('marketing_dealerprice', 'product_name',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('marketing_dealerprice', 'markup')
    # ### end Alembic commands ###
