"""Add option lazy to all models

Revision ID: 032b6ef653f2
Revises: ff73be3ab375
Create Date: 2023-12-01 04:19:40.550429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '032b6ef653f2'
down_revision: Union[str, None] = 'ff73be3ab375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
