"""Change column date in DealerPrice

Revision ID: 1d34a450a629
Revises: 02ed580b25d5
Create Date: 2023-11-27 23:28:08.023132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d34a450a629'
down_revision: Union[str, None] = '02ed580b25d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketing_dealerprice', 'date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('marketing_dealerprice', 'dealer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketing_dealerprice', 'dealer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('marketing_dealerprice', 'date',
               existing_type=sa.String(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
