"""relation4

Revision ID: 43282972fd67
Revises: f0369c5cfa46
Create Date: 2023-12-05 18:30:13.880325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43282972fd67'
down_revision: Union[str, None] = 'f0369c5cfa46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_dealerprice', sa.Column('status', postgresql.ENUM('markup', 'unclaimed', 'postponed', 'waiting', name='status_type'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketing_dealerprice', 'status')
    # ### end Alembic commands ###
