"""one-to-many

Revision ID: 871de6d9448f
Revises: c67597038ff1
Create Date: 2023-12-05 19:26:32.780706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871de6d9448f'
down_revision: Union[str, None] = 'c67597038ff1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_dealerprice', sa.Column('product_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'marketing_dealerprice', 'marketing_product', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'marketing_dealerprice', type_='foreignkey')
    op.drop_column('marketing_dealerprice', 'product_id')
    # ### end Alembic commands ###
