"""I hate this life, please work

Revision ID: 8a04f3cce2d6
Revises: 10d2d82ee23c
Create Date: 2023-11-28 00:58:39.818326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a04f3cce2d6'
down_revision: Union[str, None] = '10d2d82ee23c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketing_product', 'ean_13',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=15),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('marketing_product', 'ean_13',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=13),
               existing_nullable=True)
    # ### end Alembic commands ###
