"""Add back populates at Dealer Price

Revision ID: 9d5831cd6ef3
Revises: b9b4545d7605
Create Date: 2023-11-27 23:51:05.989120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5831cd6ef3'
down_revision: Union[str, None] = 'b9b4545d7605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
