"""one-to-many

Revision ID: c6c51ea9365c
Revises: 871de6d9448f
Create Date: 2023-12-05 19:31:00.194017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c51ea9365c'
down_revision: Union[str, None] = '871de6d9448f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('marketing_dealerprice', sa.Column('serial_number', sa.Integer(), nullable=True))
    op.add_column('marketing_dealerprice', sa.Column('date_status', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('marketing_dealerprice', 'date_status')
    op.drop_column('marketing_dealerprice', 'serial_number')
    # ### end Alembic commands ###
