"""Add back populates at Dealer Price

Revision ID: ca9988f33bdd
Revises: 9d5831cd6ef3
Create Date: 2023-11-27 23:58:19.798252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca9988f33bdd'
down_revision: Union[str, None] = '9d5831cd6ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
